"""add_admission_config_tables

Revision ID: a68ca73787ea
Revises: 26c1ead0473f
Create Date: 2026-01-04 10:01:46.021654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a68ca73787ea'
down_revision: Union[str, Sequence[str], None] = '26c1ead0473f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Method code: hoc_ba, thpt_qg, dgnl'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Method name: Xét học bạ THPT'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of method'),
    sa.Column('requires_gpa', sa.Boolean(), nullable=False, comment='Does this method require GPA input?'),
    sa.Column('requires_subject_scores', sa.Boolean(), nullable=False, comment='Does this method require subject scores?'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Display order in UI'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_method_code'), 'admission_method', ['code'], unique=True)
    op.create_index(op.f('ix_admission_method_id'), 'admission_method', ['id'], unique=False)
    op.create_index(op.f('ix_admission_method_is_active'), 'admission_method', ['is_active'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Subject code: math, physics, chemistry...'),
    sa.Column('name_vi', sa.String(length=100), nullable=False, comment='Vietnamese name: Toán, Vật lý, Hóa học...'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Display order in UI'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_code'), 'subject', ['code'], unique=True)
    op.create_index(op.f('ix_subject_id'), 'subject', ['id'], unique=False)
    op.create_index(op.f('ix_subject_is_active'), 'subject', ['is_active'], unique=False)
    op.create_table('subject_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='Group code: A00, D01, B00...'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Full name: Toán, Vật lý, Hóa học'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Display order in UI'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_group_code'), 'subject_group', ['code'], unique=True)
    op.create_index(op.f('ix_subject_group_id'), 'subject_group', ['id'], unique=False)
    op.create_index(op.f('ix_subject_group_is_active'), 'subject_group', ['is_active'], unique=False)
    op.create_table('admission_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Criteria code: HB2026_CQ, THPTQG2026_LT'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name: Xét học bạ 2026 - Chính quy'),
    sa.Column('min_gpa', sa.Numeric(precision=3, scale=1), nullable=True, comment='Minimum GPA (0.0 - 10.0)'),
    sa.Column('min_score', sa.Numeric(precision=4, scale=1), nullable=True, comment='Minimum total score (0.0 - 30.0)'),
    sa.Column('conditions', sa.Text(), nullable=True, comment='Additional conditions/notes'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['admission_method.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_criteria_code'), 'admission_criteria', ['code'], unique=True)
    op.create_index(op.f('ix_admission_criteria_id'), 'admission_criteria', ['id'], unique=False)
    op.create_index(op.f('ix_admission_criteria_is_active'), 'admission_criteria', ['is_active'], unique=False)
    op.create_index(op.f('ix_admission_criteria_method_id'), 'admission_criteria', ['method_id'], unique=False)
    op.create_table('document_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_type_id', sa.Integer(), nullable=False, comment='Link to offering type (Chính quy, Liên thông)'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Group code: HS_CHINH_QUY, HS_LIEN_THONG'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Group name: Hồ sơ chính quy'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['offering_type_id'], ['config_offering_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_group_code'), 'document_group', ['code'], unique=True)
    op.create_index(op.f('ix_document_group_id'), 'document_group', ['id'], unique=False)
    op.create_index(op.f('ix_document_group_is_active'), 'document_group', ['is_active'], unique=False)
    op.create_index(op.f('ix_document_group_offering_type_id'), 'document_group', ['offering_type_id'], unique=False)
    op.create_table('subject_group_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_group_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, comment='Position in group (1, 2, 3)'),
    sa.ForeignKeyConstraint(['subject_group_id'], ['subject_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_group_id', 'subject_id', name='uq_subject_group_subject')
    )
    op.create_index(op.f('ix_subject_group_subject_id'), 'subject_group_subject', ['id'], unique=False)
    op.create_index(op.f('ix_subject_group_subject_subject_group_id'), 'subject_group_subject', ['subject_group_id'], unique=False)
    op.create_index(op.f('ix_subject_group_subject_subject_id'), 'subject_group_subject', ['subject_id'], unique=False)
    op.create_table('criteria_subject_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('subject_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criteria_id'], ['admission_criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_group_id'], ['subject_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('criteria_id', 'subject_group_id', name='uq_criteria_subject_group')
    )
    op.create_index(op.f('ix_criteria_subject_group_criteria_id'), 'criteria_subject_group', ['criteria_id'], unique=False)
    op.create_index(op.f('ix_criteria_subject_group_id'), 'criteria_subject_group', ['id'], unique=False)
    op.create_index(op.f('ix_criteria_subject_group_subject_group_id'), 'criteria_subject_group', ['subject_group_id'], unique=False)
    op.create_table('document_group_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False, comment='Link to document type (hoc_ba, cccd)'),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False, comment='Is this document required?'),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['config_document_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['document_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'document_type_id', name='uq_document_group_item')
    )
    op.create_index(op.f('ix_document_group_item_document_type_id'), 'document_group_item', ['document_type_id'], unique=False)
    op.create_index(op.f('ix_document_group_item_group_id'), 'document_group_item', ['group_id'], unique=False)
    op.create_index(op.f('ix_document_group_item_id'), 'document_group_item', ['id'], unique=False)
    op.create_table('offering_admission_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_info_id', sa.Integer(), nullable=False, comment='Link to offering per year'),
    sa.Column('criteria_id', sa.Integer(), nullable=False, comment='Link to admission criteria'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True, comment='Config valid from (optional)'),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True, comment='Config valid until (optional)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['academic_info_id'], ['offering_academic_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criteria_id'], ['admission_criteria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_info_id', 'criteria_id', name='uq_offering_admission_config')
    )
    op.create_index(op.f('ix_offering_admission_config_academic_info_id'), 'offering_admission_config', ['academic_info_id'], unique=False)
    op.create_index(op.f('ix_offering_admission_config_criteria_id'), 'offering_admission_config', ['criteria_id'], unique=False)
    op.create_index(op.f('ix_offering_admission_config_id'), 'offering_admission_config', ['id'], unique=False)
    op.create_index(op.f('ix_offering_admission_config_is_active'), 'offering_admission_config', ['is_active'], unique=False)
    op.create_table('profile_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='missing | uploaded | verified | rejected'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='Path to uploaded file'),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True, comment='Reason if rejected'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['config_document_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['admission_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'document_type_id', name='uq_profile_document')
    )
    op.create_index(op.f('ix_profile_document_document_type_id'), 'profile_document', ['document_type_id'], unique=False)
    op.create_index(op.f('ix_profile_document_id'), 'profile_document', ['id'], unique=False)
    op.create_index(op.f('ix_profile_document_profile_id'), 'profile_document', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_document_status'), 'profile_document', ['status'], unique=False)
    op.create_table('profile_subject_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=3, scale=1), nullable=False, comment='Score 0.0 - 10.0'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['admission_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'subject_id', name='uq_profile_subject_score')
    )
    op.create_index(op.f('ix_profile_subject_score_id'), 'profile_subject_score', ['id'], unique=False)
    op.create_index(op.f('ix_profile_subject_score_profile_id'), 'profile_subject_score', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_subject_score_subject_id'), 'profile_subject_score', ['subject_id'], unique=False)
    pass  # casbin_rule managed by adapter, not Alembic
    op.add_column('admission_profile', sa.Column('offering_admission_config_id', sa.Integer(), nullable=True, comment='Source config (audit/debug/report)'))
    op.drop_constraint(op.f('uq_admission_profile_citizen_id'), 'admission_profile', type_='unique')
    op.drop_constraint(op.f('uq_admission_profile_lead_id'), 'admission_profile', type_='unique')
    op.create_index(op.f('ix_admission_profile_offering_admission_config_id'), 'admission_profile', ['offering_admission_config_id'], unique=False)
    op.create_foreign_key(None, 'admission_profile', 'offering_admission_config', ['offering_admission_config_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_allowed_transitions_from'), table_name='allowed_transitions')
    op.drop_index(op.f('idx_allowed_transitions_to'), table_name='allowed_transitions')
    op.drop_constraint(op.f('uq_transition'), 'allowed_transitions', type_='unique')
    op.alter_column('application', 'major_program_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK to MajorProgram (Tier 1) - Ngành đào tạo',
               existing_nullable=True)
    op.alter_column('application', 'program_offering_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK to ProgramOffering (Tier 2) - Loại hình đào tạo',
               existing_nullable=True)
    op.alter_column('application', 'criterion_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='ID of AdmissionCriterion from OfferingAcademicInfo.admission_criteria',
               existing_nullable=True)
    op.alter_column('application', 'documents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON: {scores: {subject: score}, checklist: [{code, label, status, submission_type, notes}]}',
               existing_nullable=True)
    op.alter_column('application', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment=None,
               existing_comment='Status: pending, missing_documents, completed, passed, failed',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('application', 'officer_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Legacy field - officer who created the application',
               existing_nullable=True)
    op.alter_column('application', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when application was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('application', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when application was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('application_lead_id_key'), 'application', type_='unique')
    op.drop_index(op.f('ix_application_lead_id'), table_name='application')
    op.create_index(op.f('ix_application_lead_id'), 'application', ['lead_id'], unique=True)
    op.alter_column('config_degree_level', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment="Mã định danh (vd: 'cao_dang', 'dai_hoc')",
               existing_comment='Mã định danh (vd: cao_dang, dai_hoc)',
               existing_nullable=False)
    op.alter_column('config_degree_level', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment="Tên hiển thị (vd: 'Cao đẳng', 'Đại học')",
               existing_comment='Tên hiển thị (vd: Cao đẳng, Đại học)',
               existing_nullable=False)
    op.drop_constraint(op.f('config_degree_level_code_key'), 'config_degree_level', type_='unique')
    op.drop_index(op.f('ix_config_degree_level_code'), table_name='config_degree_level')
    op.create_index(op.f('ix_config_degree_level_code'), 'config_degree_level', ['code'], unique=True)
    op.alter_column('config_document_type', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment="Mã định danh (vd: 'hoc_ba', 'bang_tot_nghiep')",
               existing_comment='Mã định danh (vd: "hoc_ba", "bang_tot_nghiep")',
               existing_nullable=False)
    op.alter_column('config_document_type', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment="Tên hiển thị (vd: 'Học bạ', 'Bằng tốt nghiệp')",
               existing_comment='Tên hiển thị (vd: "Học bạ", "Bằng tốt nghiệp")',
               existing_nullable=False)
    op.drop_constraint(op.f('config_document_type_code_key'), 'config_document_type', type_='unique')
    op.drop_index(op.f('idx_config_document_type_code'), table_name='config_document_type')
    op.drop_index(op.f('idx_config_document_type_is_active'), table_name='config_document_type')
    op.create_index(op.f('ix_config_document_type_code'), 'config_document_type', ['code'], unique=True)
    op.create_index(op.f('ix_config_document_type_id'), 'config_document_type', ['id'], unique=False)
    op.create_index(op.f('ix_config_document_type_is_active'), 'config_document_type', ['is_active'], unique=False)
    op.alter_column('config_offering_type', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment="Mã định danh (vd: 'chinh_quy', 'lien_thong')",
               existing_comment='Mã định danh (vd: chinh_quy, lien_thong)',
               existing_nullable=False)
    op.alter_column('config_offering_type', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment="Tên hiển thị (vd: 'Chính quy', 'Liên thông')",
               existing_comment='Tên hiển thị (vd: Chính quy, Liên thông)',
               existing_nullable=False)
    op.drop_constraint(op.f('config_offering_type_code_key'), 'config_offering_type', type_='unique')
    op.drop_index(op.f('ix_config_offering_type_code'), table_name='config_offering_type')
    op.create_index(op.f('ix_config_offering_type_code'), 'config_offering_type', ['code'], unique=True)
    op.drop_index(op.f('ix_consultation_reminder_pending'), table_name='consultation')
    op.create_index(op.f('ix_consultation_reminder_sent'), 'consultation', ['reminder_sent'], unique=False)
    op.alter_column('consultation_status', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique status identifier',
               existing_nullable=False)
    op.alter_column('consultation_status', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Display name',
               existing_nullable=False)
    op.alter_column('consultation_status', 'color_code',
               existing_type=sa.VARCHAR(length=7),
               comment='Hex color code for UI',
               existing_nullable=False)
    op.alter_column('consultation_status', 'stage_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Parent pipeline stage',
               existing_nullable=False)
    op.alter_column('consultation_status', 'outcome_type',
               existing_type=postgresql.ENUM('positive', 'neutral', 'negative', name='outcome_type_enum'),
               comment='Outcome classification: positive/neutral/negative',
               existing_comment='Outcome classification: positive (moves forward), neutral (in progress), negative (rejected/failed)',
               existing_nullable=False,
               existing_server_default=sa.text("'neutral'::outcome_type_enum"))
    op.alter_column('consultation_status', 'is_universal',
               existing_type=sa.BOOLEAN(),
               comment='True nếu status có thể dùng ở mọi pipeline stage (VD: Không nghe máy, Thuê bao)',
               existing_comment='True nếu status có thể dùng ở mọi pipeline stage (VD: Không nghe máy)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_consultation_status_universal'), table_name='consultation_status')
    op.drop_constraint(op.f('consultation_status_stage_id_fkey'), 'consultation_status', type_='foreignkey')
    op.create_foreign_key(None, 'consultation_status', 'pipeline_stage', ['stage_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_kpi_monthly_snapshot_target_id'), table_name='kpi_monthly_snapshot')
    op.create_index(op.f('ix_kpi_monthly_snapshot_kpi_target_id'), 'kpi_monthly_snapshot', ['kpi_target_id'], unique=False)
    op.alter_column('kpi_target', 'kpi_code',
               existing_type=sa.VARCHAR(length=50),
               comment="e.g., 'enrollments', 'revenue'",
               existing_comment='e.g., enrollments, revenue',
               existing_nullable=False)
    op.alter_column('kpi_target', 'last_sync_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last time achieved_ytd was synced from real data',
               existing_comment='Last time achieved_ytd was synced',
               existing_nullable=True)
    op.alter_column('lead', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email is optional - not all leads have email',
               existing_nullable=True)
    op.alter_column('lead', 'assignment_status',
               existing_type=sa.VARCHAR(length=20),
               comment='Assignment workflow: pending, assigned, failed, reassign_pending',
               existing_comment='Assignment workflow status: pending, assigned, failed, reassign_pending',
               existing_nullable=False)
    op.drop_index(op.f('ix_login_history_user_suspicious'), table_name='login_history', postgresql_where='((is_new_ip = true) OR (is_new_device = true) OR (is_new_location = true))')
    op.alter_column('major_program', 'degree_level',
               existing_type=sa.VARCHAR(length=50),
               comment="Trình độ (vd: 'Cao đẳng', 'Đại học')",
               existing_comment="Trình độ (vd: 'Cao đẳng')",
               existing_nullable=False)
    op.drop_index(op.f('idx_major_program_is_heavy'), table_name='major_program')
    op.drop_constraint(op.f('uq_major_program_code'), 'major_program', type_='unique')
    op.drop_index(op.f('ix_major_program_code'), table_name='major_program')
    op.create_index(op.f('ix_major_program_code'), 'major_program', ['code'], unique=True)
    op.create_index(op.f('ix_major_program_is_heavy'), 'major_program', ['is_heavy'], unique=False)
    op.drop_constraint(op.f('notification_preference_user_id_key'), 'notification_preference', type_='unique')
    op.alter_column('notification_rule', 'notification_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Severity: info, success, warning, error',
               existing_comment='Notification severity: info, success, warning, error',
               existing_nullable=False,
               existing_server_default=sa.text("'info'::character varying"))
    op.alter_column('notification_rule', 'recipient_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Resolver config: {resolver_type, params}',
               existing_comment='Resolver configuration: {resolver_type, params}',
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_rule_event_enabled'), table_name='notification_rule', postgresql_where='(enabled = true)')
    op.alter_column('notification_template', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Template name (human-readable)',
               existing_comment='Template name (unique identifier)',
               existing_nullable=False)
    op.alter_column('notification_template', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment="Template category (e.g., 'lead', 'consultation')",
               existing_comment='Template category (e.g., "lead", "consultation", "application")',
               existing_nullable=True)
    op.drop_constraint(op.f('uq_notification_template_code'), 'notification_template', type_='unique')
    op.alter_column('offering_academic_info', 'applied_discount_policy_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='Danh sách ID chính sách ưu đãi áp dụng (JSON array of integers)',
               existing_nullable=True)
    op.drop_index(op.f('ix_organization_unit_created_at'), table_name='organization_unit')
    op.alter_column('pipeline_stage', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique stage identifier',
               existing_nullable=False)
    op.alter_column('pipeline_stage', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Display name',
               existing_nullable=False)
    op.alter_column('pipeline_stage', 'order',
               existing_type=sa.INTEGER(),
               comment='Position in pipeline (0-based)',
               existing_nullable=False)
    op.drop_constraint(op.f('uq_student_admission_profile_id'), 'student', type_='unique')
    op.drop_constraint(op.f('uq_student_student_code'), 'student', type_='unique')
    op.drop_index(op.f('ix_trusted_device_fingerprint'), table_name='trusted_device')
    op.create_index(op.f('ix_trusted_device_device_fingerprint'), 'trusted_device', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_trusted_device_id'), 'trusted_device', ['id'], unique=False)
    op.alter_column('tuition_discount_policy', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment="Mã chính sách duy nhất (vd: 'EARLY_BIRD_2025', 'HEAVY_WORK')",
               existing_comment='Mã chính sách duy nhất (vd: EARLY_BIRD_2025)',
               existing_nullable=False)
    op.alter_column('tuition_discount_policy', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment="Tên chính sách hiển thị (vd: 'Ưu đãi đăng ký sớm 2025')",
               existing_comment='Tên chính sách hiển thị',
               existing_nullable=False)
    op.drop_index(op.f('idx_tuition_discount_policy_code'), table_name='tuition_discount_policy')
    op.drop_index(op.f('idx_tuition_discount_policy_is_active'), table_name='tuition_discount_policy')
    op.drop_index(op.f('idx_tuition_discount_policy_priority'), table_name='tuition_discount_policy')
    op.drop_index(op.f('idx_tuition_discount_policy_valid_dates'), table_name='tuition_discount_policy')
    op.drop_constraint(op.f('tuition_discount_policy_code_key'), 'tuition_discount_policy', type_='unique')
    op.create_index(op.f('ix_tuition_discount_policy_code'), 'tuition_discount_policy', ['code'], unique=True)
    op.create_index(op.f('ix_tuition_discount_policy_id'), 'tuition_discount_policy', ['id'], unique=False)
    op.create_index(op.f('ix_tuition_discount_policy_is_active'), 'tuition_discount_policy', ['is_active'], unique=False)
    op.drop_index(op.f('idx_user_email_prefix'), table_name='user', postgresql_ops={'email': 'text_pattern_ops'})
    op.drop_index(op.f('idx_user_search_vector'), table_name='user', postgresql_using='gin')
    op.drop_index(op.f('idx_user_username_prefix'), table_name='user', postgresql_ops={'username': 'text_pattern_ops'})
    op.alter_column('user_session', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_session_active_partial'), table_name='user_session', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('ix_user_session_expires_at'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_jti_unique_partial'), table_name='user_session', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('ix_user_session_revoked_at'), table_name='user_session')
    op.create_index(op.f('ix_user_session_refresh_jti'), 'user_session', ['refresh_jti'], unique=True)
    op.create_index(op.f('ix_user_unit_assignment_is_active'), 'user_unit_assignment', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_unit_assignment_role'), 'user_unit_assignment', ['role'], unique=False)
    op.create_index(op.f('ix_user_unit_assignment_unit_id'), 'user_unit_assignment', ['unit_id'], unique=False)
    op.create_index(op.f('ix_user_unit_assignment_user_id'), 'user_unit_assignment', ['user_id'], unique=False)
    op.drop_table_comment(
        'user_unit_assignment',
        existing_comment='Temporal history of user assignments to organizational units',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user_unit_assignment',
        'Temporal history of user assignments to organizational units',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_user_unit_assignment_user_id'), table_name='user_unit_assignment')
    op.drop_index(op.f('ix_user_unit_assignment_unit_id'), table_name='user_unit_assignment')
    op.drop_index(op.f('ix_user_unit_assignment_role'), table_name='user_unit_assignment')
    op.drop_index(op.f('ix_user_unit_assignment_is_active'), table_name='user_unit_assignment')
    op.drop_index(op.f('ix_user_session_refresh_jti'), table_name='user_session')
    op.create_index(op.f('ix_user_session_revoked_at'), 'user_session', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_user_session_jti_unique_partial'), 'user_session', ['refresh_jti'], unique=True, postgresql_where='(revoked_at IS NULL)')
    op.create_index(op.f('ix_user_session_expires_at'), 'user_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_session_active_partial'), 'user_session', ['user_id', 'revoked_at', 'expires_at'], unique=False, postgresql_where='(revoked_at IS NULL)')
    op.alter_column('user_session', 'user_agent',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_user_username_prefix'), 'user', ['username'], unique=False, postgresql_ops={'username': 'text_pattern_ops'})
    op.create_index(op.f('idx_user_search_vector'), 'user', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_user_email_prefix'), 'user', ['email'], unique=False, postgresql_ops={'email': 'text_pattern_ops'})
    op.drop_index(op.f('ix_tuition_discount_policy_is_active'), table_name='tuition_discount_policy')
    op.drop_index(op.f('ix_tuition_discount_policy_id'), table_name='tuition_discount_policy')
    op.drop_index(op.f('ix_tuition_discount_policy_code'), table_name='tuition_discount_policy')
    op.create_unique_constraint(op.f('tuition_discount_policy_code_key'), 'tuition_discount_policy', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tuition_discount_policy_valid_dates'), 'tuition_discount_policy', ['valid_from', 'valid_to'], unique=False)
    op.create_index(op.f('idx_tuition_discount_policy_priority'), 'tuition_discount_policy', ['priority'], unique=False)
    op.create_index(op.f('idx_tuition_discount_policy_is_active'), 'tuition_discount_policy', ['is_active'], unique=False)
    op.create_index(op.f('idx_tuition_discount_policy_code'), 'tuition_discount_policy', ['code'], unique=True)
    op.alter_column('tuition_discount_policy', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Tên chính sách hiển thị',
               existing_comment="Tên chính sách hiển thị (vd: 'Ưu đãi đăng ký sớm 2025')",
               existing_nullable=False)
    op.alter_column('tuition_discount_policy', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Mã chính sách duy nhất (vd: EARLY_BIRD_2025)',
               existing_comment="Mã chính sách duy nhất (vd: 'EARLY_BIRD_2025', 'HEAVY_WORK')",
               existing_nullable=False)
    op.drop_index(op.f('ix_trusted_device_id'), table_name='trusted_device')
    op.drop_index(op.f('ix_trusted_device_device_fingerprint'), table_name='trusted_device')
    op.create_index(op.f('ix_trusted_device_fingerprint'), 'trusted_device', ['device_fingerprint'], unique=False)
    op.create_unique_constraint(op.f('uq_student_student_code'), 'student', ['student_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_student_admission_profile_id'), 'student', ['admission_profile_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('pipeline_stage', 'order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Position in pipeline (0-based)',
               existing_nullable=False)
    op.alter_column('pipeline_stage', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Display name',
               existing_nullable=False)
    op.alter_column('pipeline_stage', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Unique stage identifier',
               existing_nullable=False)
    op.create_index(op.f('ix_organization_unit_created_at'), 'organization_unit', ['created_at'], unique=False)
    op.alter_column('offering_academic_info', 'applied_discount_policy_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Danh sách ID chính sách ưu đãi áp dụng (JSON array of integers)',
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_notification_template_code'), 'notification_template', ['template_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('notification_template', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='Template category (e.g., "lead", "consultation", "application")',
               existing_comment="Template category (e.g., 'lead', 'consultation')",
               existing_nullable=True)
    op.alter_column('notification_template', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Template name (unique identifier)',
               existing_comment='Template name (human-readable)',
               existing_nullable=False)
    op.create_index(op.f('ix_notification_rule_event_enabled'), 'notification_rule', ['event', 'enabled'], unique=False, postgresql_where='(enabled = true)')
    op.alter_column('notification_rule', 'recipient_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Resolver configuration: {resolver_type, params}',
               existing_comment='Resolver config: {resolver_type, params}',
               existing_nullable=False)
    op.alter_column('notification_rule', 'notification_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Notification severity: info, success, warning, error',
               existing_comment='Severity: info, success, warning, error',
               existing_nullable=False,
               existing_server_default=sa.text("'info'::character varying"))
    op.create_unique_constraint(op.f('notification_preference_user_id_key'), 'notification_preference', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_major_program_is_heavy'), table_name='major_program')
    op.drop_index(op.f('ix_major_program_code'), table_name='major_program')
    op.create_index(op.f('ix_major_program_code'), 'major_program', ['code'], unique=False)
    op.create_unique_constraint(op.f('uq_major_program_code'), 'major_program', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_major_program_is_heavy'), 'major_program', ['is_heavy'], unique=False)
    op.alter_column('major_program', 'degree_level',
               existing_type=sa.VARCHAR(length=50),
               comment="Trình độ (vd: 'Cao đẳng')",
               existing_comment="Trình độ (vd: 'Cao đẳng', 'Đại học')",
               existing_nullable=False)
    op.create_index(op.f('ix_login_history_user_suspicious'), 'login_history', ['user_id', 'is_new_ip', 'is_new_device', 'is_new_location'], unique=False, postgresql_where='((is_new_ip = true) OR (is_new_device = true) OR (is_new_location = true))')
    op.alter_column('lead', 'assignment_status',
               existing_type=sa.VARCHAR(length=20),
               comment='Assignment workflow status: pending, assigned, failed, reassign_pending',
               existing_comment='Assignment workflow: pending, assigned, failed, reassign_pending',
               existing_nullable=False)
    op.alter_column('lead', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email is optional - not all leads have email',
               existing_nullable=True)
    op.alter_column('kpi_target', 'last_sync_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last time achieved_ytd was synced',
               existing_comment='Last time achieved_ytd was synced from real data',
               existing_nullable=True)
    op.alter_column('kpi_target', 'kpi_code',
               existing_type=sa.VARCHAR(length=50),
               comment='e.g., enrollments, revenue',
               existing_comment="e.g., 'enrollments', 'revenue'",
               existing_nullable=False)
    op.drop_index(op.f('ix_kpi_monthly_snapshot_kpi_target_id'), table_name='kpi_monthly_snapshot')
    op.create_index(op.f('ix_kpi_monthly_snapshot_target_id'), 'kpi_monthly_snapshot', ['kpi_target_id'], unique=False)
    op.drop_constraint(None, 'consultation_status', type_='foreignkey')
    op.create_foreign_key(op.f('consultation_status_stage_id_fkey'), 'consultation_status', 'pipeline_stage', ['stage_id'], ['id'])
    op.create_index(op.f('ix_consultation_status_universal'), 'consultation_status', ['is_universal'], unique=False)
    op.alter_column('consultation_status', 'is_universal',
               existing_type=sa.BOOLEAN(),
               comment='True nếu status có thể dùng ở mọi pipeline stage (VD: Không nghe máy)',
               existing_comment='True nếu status có thể dùng ở mọi pipeline stage (VD: Không nghe máy, Thuê bao)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('consultation_status', 'outcome_type',
               existing_type=postgresql.ENUM('positive', 'neutral', 'negative', name='outcome_type_enum'),
               comment='Outcome classification: positive (moves forward), neutral (in progress), negative (rejected/failed)',
               existing_comment='Outcome classification: positive/neutral/negative',
               existing_nullable=False,
               existing_server_default=sa.text("'neutral'::outcome_type_enum"))
    op.alter_column('consultation_status', 'stage_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Parent pipeline stage',
               existing_nullable=False)
    op.alter_column('consultation_status', 'color_code',
               existing_type=sa.VARCHAR(length=7),
               comment=None,
               existing_comment='Hex color code for UI',
               existing_nullable=False)
    op.alter_column('consultation_status', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Display name',
               existing_nullable=False)
    op.alter_column('consultation_status', 'id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Unique status identifier',
               existing_nullable=False)
    op.drop_index(op.f('ix_consultation_reminder_sent'), table_name='consultation')
    op.create_index(op.f('ix_consultation_reminder_pending'), 'consultation', ['scheduled_at', 'reminder_sent'], unique=False)
    op.drop_index(op.f('ix_config_offering_type_code'), table_name='config_offering_type')
    op.create_index(op.f('ix_config_offering_type_code'), 'config_offering_type', ['code'], unique=False)
    op.create_unique_constraint(op.f('config_offering_type_code_key'), 'config_offering_type', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('config_offering_type', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Tên hiển thị (vd: Chính quy, Liên thông)',
               existing_comment="Tên hiển thị (vd: 'Chính quy', 'Liên thông')",
               existing_nullable=False)
    op.alter_column('config_offering_type', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Mã định danh (vd: chinh_quy, lien_thong)',
               existing_comment="Mã định danh (vd: 'chinh_quy', 'lien_thong')",
               existing_nullable=False)
    op.drop_index(op.f('ix_config_document_type_is_active'), table_name='config_document_type')
    op.drop_index(op.f('ix_config_document_type_id'), table_name='config_document_type')
    op.drop_index(op.f('ix_config_document_type_code'), table_name='config_document_type')
    op.create_index(op.f('idx_config_document_type_is_active'), 'config_document_type', ['is_active'], unique=False)
    op.create_index(op.f('idx_config_document_type_code'), 'config_document_type', ['code'], unique=False)
    op.create_unique_constraint(op.f('config_document_type_code_key'), 'config_document_type', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('config_document_type', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Tên hiển thị (vd: "Học bạ", "Bằng tốt nghiệp")',
               existing_comment="Tên hiển thị (vd: 'Học bạ', 'Bằng tốt nghiệp')",
               existing_nullable=False)
    op.alter_column('config_document_type', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Mã định danh (vd: "hoc_ba", "bang_tot_nghiep")',
               existing_comment="Mã định danh (vd: 'hoc_ba', 'bang_tot_nghiep')",
               existing_nullable=False)
    op.drop_index(op.f('ix_config_degree_level_code'), table_name='config_degree_level')
    op.create_index(op.f('ix_config_degree_level_code'), 'config_degree_level', ['code'], unique=False)
    op.create_unique_constraint(op.f('config_degree_level_code_key'), 'config_degree_level', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('config_degree_level', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Tên hiển thị (vd: Cao đẳng, Đại học)',
               existing_comment="Tên hiển thị (vd: 'Cao đẳng', 'Đại học')",
               existing_nullable=False)
    op.alter_column('config_degree_level', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Mã định danh (vd: cao_dang, dai_hoc)',
               existing_comment="Mã định danh (vd: 'cao_dang', 'dai_hoc')",
               existing_nullable=False)
    op.drop_index(op.f('ix_application_lead_id'), table_name='application')
    op.create_index(op.f('ix_application_lead_id'), 'application', ['lead_id'], unique=False)
    op.create_unique_constraint(op.f('application_lead_id_key'), 'application', ['lead_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('application', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when application was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('application', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when application was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('application', 'officer_id',
               existing_type=sa.INTEGER(),
               comment='Legacy field - officer who created the application',
               existing_nullable=True)
    op.alter_column('application', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='Status: pending, missing_documents, completed, passed, failed',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('application', 'documents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON: {scores: {subject: score}, checklist: [{code, label, status, submission_type, notes}]}',
               existing_nullable=True)
    op.alter_column('application', 'criterion_id',
               existing_type=sa.VARCHAR(length=100),
               comment='ID of AdmissionCriterion from OfferingAcademicInfo.admission_criteria',
               existing_nullable=True)
    op.alter_column('application', 'program_offering_id',
               existing_type=sa.INTEGER(),
               comment='FK to ProgramOffering (Tier 2) - Loại hình đào tạo',
               existing_nullable=True)
    op.alter_column('application', 'major_program_id',
               existing_type=sa.INTEGER(),
               comment='FK to MajorProgram (Tier 1) - Ngành đào tạo',
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_transition'), 'allowed_transitions', ['from_status_id', 'to_status_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_allowed_transitions_to'), 'allowed_transitions', ['to_status_id'], unique=False)
    op.create_index(op.f('idx_allowed_transitions_from'), 'allowed_transitions', ['from_status_id'], unique=False)
    op.drop_constraint(None, 'admission_profile', type_='foreignkey')
    op.drop_index(op.f('ix_admission_profile_offering_admission_config_id'), table_name='admission_profile')
    op.create_unique_constraint(op.f('uq_admission_profile_lead_id'), 'admission_profile', ['lead_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_admission_profile_citizen_id'), 'admission_profile', ['citizen_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('admission_profile', 'offering_admission_config_id')
    op.create_table('casbin_rule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ptype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v0', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v3', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v4', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v5', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('casbin_rule_pkey'))
    )
    op.drop_index(op.f('ix_profile_subject_score_subject_id'), table_name='profile_subject_score')
    op.drop_index(op.f('ix_profile_subject_score_profile_id'), table_name='profile_subject_score')
    op.drop_index(op.f('ix_profile_subject_score_id'), table_name='profile_subject_score')
    op.drop_table('profile_subject_score')
    op.drop_index(op.f('ix_profile_document_status'), table_name='profile_document')
    op.drop_index(op.f('ix_profile_document_profile_id'), table_name='profile_document')
    op.drop_index(op.f('ix_profile_document_id'), table_name='profile_document')
    op.drop_index(op.f('ix_profile_document_document_type_id'), table_name='profile_document')
    op.drop_table('profile_document')
    op.drop_index(op.f('ix_offering_admission_config_is_active'), table_name='offering_admission_config')
    op.drop_index(op.f('ix_offering_admission_config_id'), table_name='offering_admission_config')
    op.drop_index(op.f('ix_offering_admission_config_criteria_id'), table_name='offering_admission_config')
    op.drop_index(op.f('ix_offering_admission_config_academic_info_id'), table_name='offering_admission_config')
    op.drop_table('offering_admission_config')
    op.drop_index(op.f('ix_document_group_item_id'), table_name='document_group_item')
    op.drop_index(op.f('ix_document_group_item_group_id'), table_name='document_group_item')
    op.drop_index(op.f('ix_document_group_item_document_type_id'), table_name='document_group_item')
    op.drop_table('document_group_item')
    op.drop_index(op.f('ix_criteria_subject_group_subject_group_id'), table_name='criteria_subject_group')
    op.drop_index(op.f('ix_criteria_subject_group_id'), table_name='criteria_subject_group')
    op.drop_index(op.f('ix_criteria_subject_group_criteria_id'), table_name='criteria_subject_group')
    op.drop_table('criteria_subject_group')
    op.drop_index(op.f('ix_subject_group_subject_subject_id'), table_name='subject_group_subject')
    op.drop_index(op.f('ix_subject_group_subject_subject_group_id'), table_name='subject_group_subject')
    op.drop_index(op.f('ix_subject_group_subject_id'), table_name='subject_group_subject')
    op.drop_table('subject_group_subject')
    op.drop_index(op.f('ix_document_group_offering_type_id'), table_name='document_group')
    op.drop_index(op.f('ix_document_group_is_active'), table_name='document_group')
    op.drop_index(op.f('ix_document_group_id'), table_name='document_group')
    op.drop_index(op.f('ix_document_group_code'), table_name='document_group')
    op.drop_table('document_group')
    op.drop_index(op.f('ix_admission_criteria_method_id'), table_name='admission_criteria')
    op.drop_index(op.f('ix_admission_criteria_is_active'), table_name='admission_criteria')
    op.drop_index(op.f('ix_admission_criteria_id'), table_name='admission_criteria')
    op.drop_index(op.f('ix_admission_criteria_code'), table_name='admission_criteria')
    op.drop_table('admission_criteria')
    op.drop_index(op.f('ix_subject_group_is_active'), table_name='subject_group')
    op.drop_index(op.f('ix_subject_group_id'), table_name='subject_group')
    op.drop_index(op.f('ix_subject_group_code'), table_name='subject_group')
    op.drop_table('subject_group')
    op.drop_index(op.f('ix_subject_is_active'), table_name='subject')
    op.drop_index(op.f('ix_subject_id'), table_name='subject')
    op.drop_index(op.f('ix_subject_code'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_admission_method_is_active'), table_name='admission_method')
    op.drop_index(op.f('ix_admission_method_id'), table_name='admission_method')
    op.drop_index(op.f('ix_admission_method_code'), table_name='admission_method')
    op.drop_table('admission_method')
    # ### end Alembic commands ###
