"""add_criteria_rule_engine_fields

Revision ID: b907ee4279d3
Revises: a68ca73787ea
Create Date: 2026-01-04 10:34:04.235703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b907ee4279d3'
down_revision: Union[str, Sequence[str], None] = 'a68ca73787ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # casbin_rule managed by adapter, not Alembic
    op.add_column('admission_criteria', sa.Column('required_subject_count', sa.Integer(), nullable=True, comment='Số môn bắt buộc: 1, 2, 3, hoặc NULL (flexible/xét tất cả)'))
    op.add_column('admission_criteria', sa.Column('subject_selection_mode', sa.String(length=20), nullable=False, comment='fixed | best_n | any_n - Cách chọn môn từ pool'))
    op.add_column('admission_criteria', sa.Column('scoring_method', sa.String(length=20), nullable=False, comment='sum | average | weighted - Cách tính điểm'))
    op.add_column('admission_criteria', sa.Column('max_possible_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='Điểm tối đa: 30.0 (3 môn), 20.0 (2 môn), 10.0 (1 môn)'))
    op.add_column('admission_criteria', sa.Column('min_subject_score', sa.Numeric(precision=3, scale=1), nullable=True, comment='Điểm tối thiểu mỗi môn (vd: không môn nào dưới 1.0)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admission_criteria', 'min_subject_score')
    op.drop_column('admission_criteria', 'max_possible_score')
    op.drop_column('admission_criteria', 'scoring_method')
    op.drop_column('admission_criteria', 'subject_selection_mode')
    op.drop_column('admission_criteria', 'required_subject_count')
    op.create_table('casbin_rule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ptype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v0', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v3', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v4', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v5', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('casbin_rule_pkey'))
    )
    # ### end Alembic commands ###
