"""add_criteria_check_constraints

Revision ID: bd234d6fb095
Revises: b907ee4279d3
Create Date: 2026-01-04 10:40:44.254573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd234d6fb095'
down_revision: Union[str, Sequence[str], None] = 'b907ee4279d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casbin_rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_rule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ptype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v0', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v3', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v4', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('v5', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('casbin_rule_pkey'))
    )
    # ### end Alembic commands ###
