"""Initial migration - create all tables

Revision ID: ec2713f8825b
Revises: 
Create Date: 2025-10-26 12:17:57.261227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2713f8825b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_unit_id'), 'organization_unit', ['id'], unique=False)
    op.create_table('pipeline_stage',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order')
    )
    op.create_table('skill_requirement_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_attribute', sa.String(length=100), nullable=False),
    sa.Column('attribute_value', sa.String(length=255), nullable=False),
    sa.Column('required_skill', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_requirement_rule_id'), 'skill_requirement_rule', ['id'], unique=False)
    op.create_table('consultation_status',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color_code', sa.String(length=7), nullable=False),
    sa.Column('stage_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_scoring_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['organization_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id')
    )
    op.create_index(op.f('ix_lead_scoring_config_id'), 'lead_scoring_config', ['id'], unique=False)
    op.create_table('major',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['organization_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_major_id'), 'major', ['id'], unique=False)
    op.create_table('officer_assignment_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['organization_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id')
    )
    op.create_index(op.f('ix_officer_assignment_config_id'), 'officer_assignment_config', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=256), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('active_jti', sa.String(length=36), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('availability_status', sa.String(length=50), nullable=True),
    sa.Column('total_lead_score', sa.Integer(), nullable=False),
    sa.Column('last_assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['organization_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_active_jti'), 'user', ['active_jti'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('officer_rating', sa.Integer(), nullable=True),
    sa.Column('officer_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('consultation_status_id', sa.String(length=50), nullable=True),
    sa.Column('pipeline_stage_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['consultation_status_id'], ['consultation_status.id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.ForeignKeyConstraint(['pipeline_stage_id'], ['pipeline_stage.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['organization_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_assigned_officer_id'), 'lead', ['assigned_officer_id'], unique=False)
    op.create_index(op.f('ix_lead_email'), 'lead', ['email'], unique=False)
    op.create_index(op.f('ix_lead_id'), 'lead', ['id'], unique=False)
    op.create_index(op.f('ix_lead_phone'), 'lead', ['phone'], unique=False)
    op.create_index(op.f('ix_lead_pipeline_stage_id'), 'lead', ['pipeline_stage_id'], unique=False)
    op.create_index(op.f('ix_lead_status'), 'lead', ['status'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_table('assignment_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('consultation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('consultation_status_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['consultation_status_id'], ['consultation_status.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_consultation_date'), 'consultation', ['consultation_date'], unique=False)
    op.create_index(op.f('ix_consultation_id'), 'consultation', ['id'], unique=False)
    op.create_index(op.f('ix_consultation_lead_id'), 'consultation', ['lead_id'], unique=False)
    op.create_table('crm_interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('old_consultation_status_id', sa.String(length=50), nullable=True),
    sa.Column('new_consultation_status_id', sa.String(length=50), nullable=True),
    sa.Column('old_pipeline_stage_id', sa.String(length=50), nullable=True),
    sa.Column('new_pipeline_stage_id', sa.String(length=50), nullable=True),
    sa.Column('old_assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('new_assigned_officer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['new_assigned_officer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['new_consultation_status_id'], ['consultation_status.id'], ),
    sa.ForeignKeyConstraint(['new_pipeline_stage_id'], ['pipeline_stage.id'], ),
    sa.ForeignKeyConstraint(['old_assigned_officer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['old_consultation_status_id'], ['consultation_status.id'], ),
    sa.ForeignKeyConstraint(['old_pipeline_stage_id'], ['pipeline_stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_status_history_changed_at'), 'lead_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_lead_status_history_id'), 'lead_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_lead_status_history_lead_id'), 'lead_status_history', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_status_history_new_status'), 'lead_status_history', ['new_status'], unique=False)
    op.create_index(op.f('ix_lead_status_history_old_status'), 'lead_status_history', ['old_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_status_history_old_status'), table_name='lead_status_history')
    op.drop_index(op.f('ix_lead_status_history_new_status'), table_name='lead_status_history')
    op.drop_index(op.f('ix_lead_status_history_lead_id'), table_name='lead_status_history')
    op.drop_index(op.f('ix_lead_status_history_id'), table_name='lead_status_history')
    op.drop_index(op.f('ix_lead_status_history_changed_at'), table_name='lead_status_history')
    op.drop_table('lead_status_history')
    op.drop_table('crm_interaction')
    op.drop_index(op.f('ix_consultation_lead_id'), table_name='consultation')
    op.drop_index(op.f('ix_consultation_id'), table_name='consultation')
    op.drop_index(op.f('ix_consultation_consultation_date'), table_name='consultation')
    op.drop_table('consultation')
    op.drop_table('assignment_log')
    op.drop_table('application')
    op.drop_index(op.f('ix_lead_status'), table_name='lead')
    op.drop_index(op.f('ix_lead_pipeline_stage_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_phone'), table_name='lead')
    op.drop_index(op.f('ix_lead_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_email'), table_name='lead')
    op.drop_index(op.f('ix_lead_assigned_officer_id'), table_name='lead')
    op.drop_table('lead')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_active_jti'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_officer_assignment_config_id'), table_name='officer_assignment_config')
    op.drop_table('officer_assignment_config')
    op.drop_index(op.f('ix_major_id'), table_name='major')
    op.drop_table('major')
    op.drop_index(op.f('ix_lead_scoring_config_id'), table_name='lead_scoring_config')
    op.drop_table('lead_scoring_config')
    op.drop_table('consultation_status')
    op.drop_index(op.f('ix_skill_requirement_rule_id'), table_name='skill_requirement_rule')
    op.drop_table('skill_requirement_rule')
    op.drop_table('pipeline_stage')
    op.drop_index(op.f('ix_organization_unit_id'), table_name='organization_unit')
    op.drop_table('organization_unit')
    # ### end Alembic commands ###
