"""add enrollment_letter table (official "Giấy báo nhập học" issuance record)

One row per official admission letter issued for a post-decision profile:
snapshots the officer-entered enrollment window + the rendered data, and records
the persisted PDF (path + sha256 + size + retention) with who/when. Hand-written
(not autogenerated) to avoid sweeping in unrelated dev-DB drift.

Revision ID: enroll_letter_20260718
Revises: consultacctdeny20260716
Create Date: 2026-07-18
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "enroll_letter_20260718"
down_revision = "consultacctdeny20260716"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "enrollment_letter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("enrollment_start_date", sa.Date(), nullable=False),
        sa.Column("enrollment_end_date", sa.Date(), nullable=False),
        sa.Column(
            "data_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("generated_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["admission_profile.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_id"], ["user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_enrollment_letter_id"), "enrollment_letter", ["id"]
    )
    op.create_index(
        "ix_enrollment_letter_profile_id", "enrollment_letter", ["profile_id"]
    )
    op.create_index(
        "ix_enrollment_letter_generated_by_id",
        "enrollment_letter",
        ["generated_by_id"],
    )
    op.create_index(
        "ix_enrollment_letter_expires_at", "enrollment_letter", ["expires_at"]
    )


def downgrade() -> None:
    op.drop_index(
        "ix_enrollment_letter_expires_at", table_name="enrollment_letter"
    )
    op.drop_index(
        "ix_enrollment_letter_generated_by_id", table_name="enrollment_letter"
    )
    op.drop_index(
        "ix_enrollment_letter_profile_id", table_name="enrollment_letter"
    )
    op.drop_index(
        op.f("ix_enrollment_letter_id"), table_name="enrollment_letter"
    )
    op.drop_table("enrollment_letter")
