# app/models/admission_config/admission_path.py
"""
Admission Path Model.

FIRST-CLASS ENTITY representing a complete admission pathway:
Year + Major + Offering + Method = AdmissionPath

This is the CENTRAL ENTITY for:
- Wizard configuration
- Matrix display
- Activation control
"""

import sqlalchemy as sa
from sqlalchemy import CheckConstraint, Column, Integer, String, Boolean, ForeignKey, DateTime, UniqueConstraint, Numeric
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
from typing import TYPE_CHECKING

from app.models.base import Base

if TYPE_CHECKING:
    from app.models.offering_academic_info import OfferingAcademicInfo
    from app.models.admission_config.method import AdmissionMethod
    from app.models.admission_config.criteria import AdmissionCriteria
    from app.models.user import User


class AdmissionPath(Base):
    """
    Đường tuyển sinh = Năm học + Ngành + Chương trình + Phương thức.
    
    This is the CENTRAL ENTITY that UI revolves around.
    
    Examples:
        - "CNTT 2026 – Chính quy – Xét học bạ"
        - "CNTT 2026 – Chính quy – THPT Quốc gia"
        - "CNTT 2026 – Chính quy – ĐGNL"
    
    Status Lifecycle:
        draft → active → inactive → archived
    
    Activation Guard:
        Can only activate if:
        - Has criteria (min_gpa OR min_score)
        - Has document config
        - Has quota > 0
    """
    __tablename__ = "admission_path"

    id = Column(Integer, primary_key=True, index=True)
    
    # Context
    academic_info_id = Column(
        Integer,
        ForeignKey("offering_academic_info.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Link to offering per year (Year + Major + Offering)"
    )
    admission_method_id = Column(
        Integer,
        ForeignKey("admission_method.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Link to admission method (hoc_ba, thpt_qg, dgnl)"
    )
    
    # Criteria (for efficient eager loading - avoids N+1)
    # ADM-003: UNIQUE invariant — each AdmissionCriteria row belongs to
    # exactly one AdmissionPath. The constraint itself is declared in
    # ``__table_args__`` below as
    # ``UniqueConstraint(name="uq_admission_path_criteria_id")`` so it
    # matches the alembic adm003path001 migration's named constraint
    # exactly. Column-level ``unique=True`` would instead produce a
    # SQLAlchemy-autogenerated UNIQUE INDEX (``ix_admission_path_*``)
    # whose name diverges from the migration → repeated alembic
    # autogenerate churn. ``index=True`` is kept so the existing
    # non-unique perf index ``ix_admission_path_criteria_id`` (created
    # by a68ca73787ea well before ADM-003) is preserved on autogenerate.
    criteria_id = Column(
        Integer,
        ForeignKey("admission_criteria.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="Link to admission criteria (nullable for draft paths). "
                "UNIQUE: each criteria belongs to exactly one path (ADM-003).",
    )
    
    # State
    status = Column(
        String(20),
        nullable=False,
        default="draft",
        index=True,
        comment="Status: draft | active | inactive | archived"
    )
    
    # Metadata
    display_name = Column(
        String(255),
        nullable=True,
        comment="Human-readable name: 'CNTT 2026 – CQ – Học bạ'"
    )
    display_order = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Display order in UI"
    )
    visibility = Column(
        String(20),
        nullable=False,
        default="internal",
        comment="Visibility: internal | public (for future portal)"
    )

    # Application Fee Configuration
    application_fee = Column(
        Numeric(precision=12, scale=2),
        nullable=True,
        default=None,
        comment="Lệ phí xét tuyển (VND). 0 hoặc NULL = miễn phí"
    )

    # PR #6 — per-path relaxation of the verified-docs submit rule.
    # Default False (strict) for new paths; the alembic migration set
    # existing paths to True so pre-PR profiles keep submitting.
    allow_unverified_submission = Column(
        Boolean,
        nullable=False,
        default=False,
        server_default=sa.false(),
        comment=(
            "When True, the submit validator accepts documents in "
            "`uploaded` status. When False (default), only `verified` "
            "or `paper_submitted` count toward submission."
        ),
    )

    # Per-path allowlist for post-approval minor corrections (governance setting).
    # Empty default = no corrections allowed. Admin opts in field-by-field per
    # path. Effective allowlist = SAFE_MINOR_CORRECTION_FIELDS ∩ this list,
    # so admin cannot widen scope beyond the system-level safe catalog.
    # NOT snapshotted to AdmissionProfile.applied_rules: admin changes apply
    # live across all profiles attached to the path (different from PR #6's
    # allow_unverified_submission which IS snapshotted).
    minor_correction_allowed_fields = Column(
        JSONB,
        nullable=False,
        default=list,
        server_default=sa.text("'[]'::jsonb"),
        comment=(
            "Per-path allowlist for post-approval minor corrections. "
            "Effective = SAFE_MINOR_CORRECTION_FIELDS ∩ this list. "
            "Live config (not snapshotted to applied_rules)."
        ),
    )

    # phase1_02 (#184 Wave 1) — path-level bonus rule override above
    # the method default. Same JSONB shape as
    # AdmissionMethod.default_bonus_rule. NULL = inherit from method.
    # Resolution precedence (PLAN line 787-789):
    #   effective = path.bonus_rule_override
    #               ?? method.default_bonus_rule
    #               ?? {"apply_area_bonus": false, "apply_subject_bonus": false}
    bonus_rule_override = Column(
        JSONB,
        nullable=True,
        comment="Path-level bonus rule override above method default. "
                "NULL = inherit from admission_method.default_bonus_rule."
    )

    @property
    def requires_application_fee(self) -> bool:
        """Check if this admission path requires application fee payment."""
        return self.application_fee is not None and float(self.application_fee) > 0

    # Activation Audit
    activated_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="When was this path activated"
    )
    activated_by = Column(
        Integer,
        ForeignKey("user.id", ondelete="SET NULL"),
        nullable=True,
        comment="Who activated this path"
    )
    
    # Timestamps
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc)
    )
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    academic_info = relationship(
        "OfferingAcademicInfo",
        back_populates="admission_paths"
    )
    admission_method = relationship(
        "AdmissionMethod",
        back_populates="admission_paths"
    )
    criteria = relationship(
        "AdmissionCriteria",
        foreign_keys="[AdmissionPath.criteria_id]"
    )
    activator = relationship(
        "User",
        foreign_keys=[activated_by]
    )

    # UNIQUE constraint: Only 1 path per (offering + method)
    # ADM-003 UNIQUE constraint: criteria_id is path-owned. Named to
    # match alembic adm003path001 so future autogenerate diffs stay
    # quiet (the migration creates this exact constraint name).
    __table_args__ = (
        UniqueConstraint(
            "academic_info_id", "admission_method_id",
            name="uq_admission_path_offering_method"
        ),
        UniqueConstraint(
            "criteria_id",
            name="uq_admission_path_criteria_id",
        ),
        CheckConstraint(
            "status IN ('draft','active','inactive','archived')",
            name="ck_admission_path_status"
        ),
    )

    def __repr__(self):
        return f"<AdmissionPath {self.id}: {self.display_name or 'unnamed'} ({self.status})>"
